config/routes.rb
HopeCincy::Application.routes.draw do
  devise_for :users

  root :to => "site#index"

  resources :organizations, :only => [:create, :show]
  match '/organizations/new(/:org_type)' => 'organizations#new', :as => :new_organization

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable, :timeoutable and :oauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  respond_to :html

  def new
    @organization = Organization.new(:donor => (params[:org_type] == 'donor'))
    respond_with @organization
  end

  def create
    @organization = Organization.new(params[:organization])
    if @organization.save
      flash[:notice] = 'Your organization was submitted for approval!'
    else
      flash[:error] = "We weren't able to submit your organization. Please check the errors below"
    end
    respond_with(@organization, :location => root_path)
  end

  def show

  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.haml
!!! XML
!!!
%html{:'xml:lang' => "en", :lang => "en"}
  %head
    %title= "#{controller.class.to_s}: #{controller.action_name}"
    %meta{:"http-equiv" => "Content-Type", :content => "text/html; charset=utf-8"}
    %link{:rel => "shortcut icon", :href => "/favicon.ico"}
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'print.css', :media => 'print'
    /[if lt IE 8]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'    
    - if Rails.env.production?
      = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js'
    - else
      = javascript_include_tag 'http://code.jquery.com/jquery-1.4.2.js'
    :javascript
      $(document).ready(function() {
        $("form#new_organization").validate();
      });
  %body.bp.two-col
    #container
      #header
        %h1
          = link_to('Hope Worldwide', root_path)
        #account
          - if user_signed_in?
            = "Hi, #{current_user.email}"
            |
            = link_to('Sign Out', destroy_user_session_path)
          - else
            = link_to('Sign Up', new_user_registration_path)
            |
            = link_to('Sign In', new_user_session_path)
      #content
        - flash.each_pair do |level, value|
          = content_tag(:div, value, :class => "flash #{level}")
        = yield
      #sidebar
        %p
          Go back
          = link_to('home', root_path)
      #footer
        %p
          Designed and developed by 
          = link_to('26Webs LLC', 'http://26Webs.com/')
          for Hope WorldWide Cincinnati.

app/views/organizations/new.html.haml
%h2 Add Organization
= semantic_form_for(@organization, :html => { :class => 'bp' }) do |f|
  = f.inputs do
    = f.inputs
  = f.buttons do
    = f.commit_button

app/views/site/index.html.haml
#registration
  %h2 Sign Up
  = link_to('Sign Up', new_user_registration_path, :class => 'button')
#recipients
  %h2 Sign Up
  = link_to('Sign Up', new_organization_path(:org_type => 'recipient'), :class => 'button')

app/views/users/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.oauthable?
  - resource_class.oauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", oauth_authorize_url(resource_name, provider)
    %br/